### ISSUE TITLE
barplot_columns 'noviolin' option throws an error

### ISSUE THREAD

**Issue by yonestar** [canlab/CanlabCore#22]
To reproduce error:

a = [
 19.0000   29.6667   21.3333   23.4667
   14.6667   27.9333   53.0667   60.6667
   58.9333   61.4667   70.8000   75.6667
   70.8667   85.5333   75.6667   89.6667
   25.0667   33.2000   51.0000   74.2000
   42.8667   65.9333   76.6000   93.4000
   19.2000   31.4667   55.4667   55.6000];

barplot_columns(a, 'noviolin');

OUTPUT:

Index exceeds matrix dimensions.

Error in barplot_columns (line 515)
            mycolcolor = mycolor(i, :) ./ 2;

**Comment by torwager** [comment]
Fixed - error with colors in some cases.TorOn Sep 3, 2017, at 8:07 PM, Yoni Ashar <notifications@github.com> wrote:To reproduce error:a = [
19.0000   29.6667   21.3333   23.4667
14.6667   27.9333   53.0667   60.6667
58.9333   61.4667   70.8000   75.6667
70.8667   85.5333   75.6667   89.6667
25.0667   33.2000   51.0000   74.2000
42.8667   65.9333   76.6000   93.4000
19.2000   31.4667   55.4667   55.6000];barplot_columns(a, 'noviolin');OUTPUT:Index exceeds matrix dimensions.Error in barplot_columns (line 515)
mycolcolor = mycolor(i, :) ./ 2;—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/canlab/CanlabCore","title":"canlab/CanlabCore","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/canlab/CanlabCore" class="">https://github.com/canlab/CanlabCore</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"barplot_columns 'noviolin' option throws an error (#22)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/canlab/CanlabCore/issues/22" class="">https://github.com/canlab/CanlabCore/issues/22</a>"}}}
