### ISSUE TITLE
roc_plot p-values

### ISSUE THREAD

**Issue by yonestar** [canlab/CanlabCore#9]
When the number of hits is equal to exactly half the number of trials, roc_plot returns a p-value greater than 1.

The error is in the function binotest.m line 24.  To simulate, simply run:

binotest([0 0 1 1]', .5)

Its taking the cdf of getting at least 1/2 hits, which is greater than .5, and then multiplying that value by 2, yielding a pval > 1.   I'm not sure what the right fix is.

**Comment by wanirepo** [comment]
Maybe, if p >= 1, you can say p = 1? It seems p > 1 is because it is calculating "two"-tailed P-value (by multiplying by 2). If this sounds okay, we can add one line of code for if p >=1, then p = 1.

**Comment by wanirepo** [comment]
Maybe, if p >= 1, you can say p = 1? It seems p > 1 is because it is
calculating "two"-tailed P-value (by multiplying by 2). If this sounds
okay, we can add one line of code for if p >=1, then p = 1.

On Fri, Aug 28, 2015 at 1:17 PM, Yoni Ashar <notifications@github.com>
wrote:

> When the number of hits is equal to exactly half the number of trials,
> roc_plot returns a p-value greater than 1.
>
> The error is in the function binotest.m line 24. To simulate, simply run:
>
> binotest([0 0 1 1]', .5)
>
> Its taking the cdf of getting at least 1/2 hits, which is greater than .5,
> and then multiplying that value by 2, yielding a pval > 1. I'm not sure
> what the right fix is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/canlab/CanlabCore/issues/9>.
>



-- 
Choong-Wan (Wani) Woo
Web <http://wanirepo.github.io/> | Code <https://github.com/wanirepo/> | Google
Scholar <https://scholar.google.com/citations?user=fZLY5H8AAAAJ&hl=en&oi=ao>
| Lab <http://wagerlab.colorado.edu/>
PhD candidate
Cognitive and Affective Neuroscience Lab
University of Colorado Boulder

**Comment by yonestar** [comment]
is p == 1 the 'correct' p-value for this case?  actually, thinking about it now, I think we need:

if p > 1, p = p / 2.

that sort of "undoes" the attempt to make it two-tailed on line 24 of binotest; there is no two-tails, perhaps, if # of hits is exactly half the number of trials.  what do you think?

**Comment by yonestar** [comment]
thinking about if further, maybe it is correct to set p to 1.  p = 1 means:

if the null is true, we would observe this result--OR A MORE EXTREME RESULT--100% of the time.

since this result is the middle of the distribution, a more extreme result is actually *any other* result.  and there is in fact a 100% chance of getting this result or a more extreme result (i.e., any other result).

**Comment by wanirepo** [comment]
Hey, Yoni. What I thought was, 

if p > 1, p = 1

not p = p / 2

I agree with your stream of thoughts.

**Comment by yonestar** [comment]
thanks Wani.  I am making this change
